services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html